CREATE USER todo_write;

GRANT CONNECT ON DATABASE todos TO todo_write;

GRANT USAGE ON SCHEMA public TO todo_write;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO todo_write;

GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO todo_write;

